[dev]
65.0.30.201
13.206.207.63

[prod]
13.234.37.146
13.207.2.89

[stage]
43.204.29.139
13.233.164.173

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/appKey
ansible_python_interpreter=/usr/bin/python3

[dev:vars]
env=dev

[prod:vars]
env=prod

[stage:vars]
env=stage

